import React from "react";
import Herosec from "../components/herosec";

const Page = () => {
  return <Herosec title={"OUR STORY"} imageUrl={"/about1.svg"} />;
};

export default Page;

export const metadata = {
  title: "SuDiPtA-Flix-About",
  description: "Generated by create next app",
};
