import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Sessionwrapper from "./components/sessionwrapper";

const mulish = Mulish({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Sessionwrapper>
        <body className={mulish.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </Sessionwrapper>
    </html>
  );
}
